updates:
  - package-ecosystem: "pip"
    assignees:
      - "EDM115"
    commit-message:
      include: scope
      prefix: "[dependabot/pip] "
    directory: "/"
    labels:
      - "dependabot/pip"
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "EDM115"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "20:00"
      timezone: "Europe/Paris"
version: 2
