name: Unfurl Links

on:
  #issues:
    #types: [opened, edited]
  #issue_comment:
    #types: [created, edited]
  #pull_request:
    #types: [opened, edited]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/unfurl-links@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          raw: false
